### PR TITLE
Added option to authenticate using bearer token

### PR DESCRIPTION
**Pull request by Fank**
A similar PR may already be submitted!
Please search among the [pull requests](../../../pulls) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

For more information, see the [CONTRIBUTING](CONTRIBUTING.md) guide.

**Summary**

This pull request includes a change to the `client.go` file to add a new method for setting Bearer token authentication.

Authentication improvements:

* [`client.go`](diffhunk://#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfR96-R99): Added the `SetBearerToken` method to allow setting Bearer token authentication in the request headers.

This PR fixes/implements the following **bugs/features**

When running gotenberg in a google cloud run instance with authentication enabled, i need to send a bearer token in order to be able to authenticate.
This PR implements the option to provide a bearer token for authentication.

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output.

**Closing issues**

Fixes #

**Checklist**

- [ ] Have you followed the guidelines in our [CONTRIBUTING](CONTRIBUTING.md) guide?
- [ ] Have you lint your code locally prior to submission (`make lint`)?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally (`make tests`)?
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code

### CODE REVIEW

**Comment by dcaraxes** [comment]
As far as I know, Gotenberg does not support bearer token authorization, only basic. If this is not the case, please provide a link to the release notes or a paragraph in the documentation stating the opposite.

**Comment by Fank** [comment]
Ah i maybe missed the background information.
Its not for gotenberg directly, its for google cloud.
In this case, i am running gotenberg als google cloud run service with authentication enabled and gotenberg without authentication.
To authenticate against google i need to send a Bearer token to authenticate.
This is why i implemented another option for authentication.

**Comment by Fank** [comment]
You are right, my issue can be fixed by provding a http.Transport which adds the Authentication i need.
Since its not part of gotenberg i am closing this.

**Comment by Fank** [comment]
I will leave the copilot example here for others:

Yes, you can add an Authentication header for each request in `http.Client` in Go by using a custom transport. Here's an example of how you can do this:

```go
package main

import (
    "net/http"
)

// CustomTransport is a custom HTTP transport that adds an Authorization header to each request.
type CustomTransport struct {
    Transport http.RoundTripper
    Token     string
}

// RoundTrip executes a single HTTP transaction and adds the Authorization header.
func (t *CustomTransport) RoundTrip(req *http.Request) (*http.Response, error) {
    req.Header.Set("Authorization", "Bearer "+t.Token)
    return t.Transport.RoundTrip(req)
}

func main() {
    // Create a custom transport with your token.
    customTransport := &CustomTransport{
        Transport: http.DefaultTransport,
        Token:     "your-authentication-token",
    }

    // Create an HTTP client with the custom transport.
    client := &http.Client{
        Transport: customTransport,
    }

    // Use the client to make a request.
    resp, err := client.Get("https://api.example.com/data")
    if err != nil {
        // Handle error
    }
    defer resp.Body.Close()

    // Process the response...
}
```

In this example:
- A custom transport (`CustomTransport`) is defined that adds an `Authorization` header with a bearer token to each request.
- This custom transport is then used in an `http.Client` instance.
- Any requests made with this client will include the `Authorization` header.

**Pull request closed without merging**
